
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain test_domain)
    (:requirements :typing :equality)
    (:types
        tealeavesquality - object
        object
    )

    (:constants
        
    )

    (:predicates
        (extendedarm )
        (tea-made )
        (tea-made-with ?x1 - tealeavesquality)
        (on-upper-shelf ?x1 - tealeavesquality)
        (on-lower-shelf ?x1 - tealeavesquality)
        (in-kitchen )
        (has-tealeaves ?x1 - tealeavesquality)
        (can_climb )
        (ladder-next-pantry )
        (ladder-used )
        (dummy )
    )

    (:functions
        
    )

    

    
    (:action bring_ladder
     :parameters ()
     :precondition (in-kitchen )
     :effect (and
        (ladder-next-pantry ))
    )


    (:action grab_tealeaves
     :parameters (?n - tealeavesquality)
     :precondition (and (on-lower-shelf ?n) (in-kitchen ))
     :effect (and
        (has-tealeaves ?n))
    )


    (:action reach_tealeaves_extend_arm
     :parameters (?g - tealeavesquality)
     :precondition (and (on-upper-shelf ?g) (in-kitchen ))
     :effect (and
        (extendedarm )
        (has-tealeaves ?g))
    )


    (:action reach_tealeaves_ladder
     :parameters (?g - tealeavesquality)
     :precondition (and (ladder-next-pantry ) (on-upper-shelf ?g) (can_climb ))
     :effect (and
        (has-tealeaves ?g)
        (ladder-used ))
    )


    (:action make_tea
     :parameters (?t - tealeavesquality)
     :precondition (has-tealeaves ?t)
     :effect (and
        (tea-made )
        (tea-made-with ?t))
    )

)