
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        goodquality normalquality - tealeavesquality
    )

    (:init
        (in-kitchen )
        (on-upper-shelf goodquality)
        (on-lower-shelf normalquality)
        (dummy )
    )

    (:goal
        (and (on-lower-shelf normalquality) (has-tealeaves goodquality) (in-kitchen ) (dummy ) (tea-made ) (tea-made-with goodquality))
    )

    
    
    
)

