
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        driver1 driver2 driver3 - driver
        p0-1 p0-2 p1-2 s0 s1 s2 - location
        package1 package2 package3 package4 package5 - obj
        truck1 truck2 - truck
    )

    (:init
        (at package1 s0)
        (at truck2 s1)
        (at package4 s2)
        (at package3 s2)
        (at driver1 s1)
        (at package5 s1)
        (at truck1 s1)
        (at package2 s0)
        (at driver2 s0)
        (at driver3 s0)
        (empty truck2)
        (empty truck1)
        (path p1-2 s2)
        (path p0-2 s2)
        (path p0-1 s0)
        (path p1-2 s1)
        (path p0-1 s1)
        (path s0 p0-2)
        (path p0-2 s0)
        (path s1 p1-2)
        (path s2 p1-2)
        (path s0 p0-1)
        (path s2 p0-2)
        (link s1 s2)
        (link s1 s0)
        (link s0 s2)
        (link s2 s0)
        (link s0 s1)
        (link s2 s1)
    )

    (:goal
        (and (at package4 s0) (at driver2 s2) (at truck2 s2) (at truck1 s2) (at package3 s1) (at package1 s1) (at package5 s1))
    )

    
    
    
)

