
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        a b c d e - block
    )

    (:init
        (clear d)
        (clear c)
        (ontable d)
        (ontable a)
        (on b a)
        (on c e)
        (on e b)
        (handempty )
    )

    (:goal
        (and (on d c) (on e b) (on b d) (on a e))
    )

    
    
    
)

