
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        a b c d e - block
    )

    (:init
        (clear e)
        (clear c)
        (clear b)
        (ontable d)
        (ontable e)
        (ontable c)
        (on a d)
        (on b a)
        (handempty )
    )

    (:goal
        (and (on b a) (on a e) (on c b) (on d c))
    )

    
    
    
)

