
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        apn1 - airplane
        apt1 apt2 - airport
        cit1 cit2 - city
        pos1 pos2 - location
        obj11 obj12 obj13 obj21 obj22 obj23 - package
        tru1 tru2 - truck
    )

    (:init
        (at apn1 apt2)
        (at obj21 pos2)
        (at obj13 pos1)
        (at tru1 pos1)
        (at tru2 pos2)
        (at obj23 pos2)
        (at obj12 pos1)
        (at obj22 pos2)
        (at obj11 pos1)
        (in-city pos2 cit2)
        (in-city pos1 cit1)
        (in-city apt1 cit1)
        (in-city apt2 cit2)
    )

    (:goal
        (and (at obj12 apt2) (at obj21 apt2) (at obj11 pos2))
    )

    
    
    
)

