
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        driver1 driver2 - driver
        p1-0 p1-2 s0 s1 s2 - location
        package1 package2 - obj
        truck1 truck2 - truck
    )

    (:init
        (at truck2 s0)
        (at driver1 s2)
        (at truck1 s0)
        (at package1 s0)
        (at package2 s0)
        (at driver2 s2)
        (empty truck1)
        (empty truck2)
        (path p1-0 s1)
        (path s0 p1-0)
        (path s2 p1-2)
        (path s1 p1-2)
        (path s1 p1-0)
        (path p1-2 s1)
        (path p1-2 s2)
        (path p1-0 s0)
        (link s1 s2)
        (link s0 s1)
        (link s2 s0)
        (link s1 s0)
        (link s2 s1)
        (link s0 s2)
    )

    (:goal
        (and (at package1 s0) (at package2 s0) (at driver1 s1))
    )

    
    
    
)

