
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        a b c d - block
    )

    (:init
        (clear b)
        (ontable d)
        (on c a)
        (on a d)
        (handempty )
    )

    (:goal
        (and (on d c) (on c a) (on a b))
    )

    
    
    
)

